# Generated by Django 5.2.4 on 2025-10-19 12:03

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_timetable_departmentaldues_academiccalendar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('institution', models.CharField(help_text='University/Organization', max_length=200)),
                ('qualification', models.CharField(help_text='e.g., B.Eng, M.Sc, Ph.D', max_length=200)),
                ('area_of_expertise', models.CharField(max_length=200)),
                ('reason_for_contribution', models.TextField()),
                ('password', models.CharField(max_length=128)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_guests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Guest Contributors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('abstract', models.TextField(help_text='Brief overview of the research')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('In Progress', 'In Progress'), ('Under Review', 'Under Review'), ('Published', 'Published')], default='Draft', max_length=20)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('views_count', models.IntegerField(default=0)),
                ('likes_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Research Articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('references', models.TextField(blank=True, help_text='References used in this section', null=True)),
                ('section_order', models.IntegerField(default=0, help_text='Order in the article')),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contributions', to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.researcharticle')),
                ('guest_contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_contributions', to='core.guestcontributor')),
                ('student_contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_contributions', to='core.student')),
            ],
            options={
                'verbose_name_plural': 'Research Contributions',
                'ordering': ['section_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('question', models.TextField()),
                ('difficulty_level', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Expert', 'Expert')], default='Medium', max_length=20)),
                ('category', models.CharField(help_text='e.g., Biomechanics, Signal Processing', max_length=100)),
                ('hints', models.TextField(blank=True, help_text='Optional hints for participants', null=True)),
                ('points', models.IntegerField(default=10, help_text='Points awarded for correct answer')),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Research Quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Team Alpha, Team Beta', max_length=100, unique=True)),
                ('description', models.TextField()),
                ('focus_area', models.CharField(help_text='e.g., Medical Imaging, Biomechanics', max_length=200)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('is_active', models.BooleanField(default=True)),
                ('max_members', models.IntegerField(default=15, help_text='Maximum team members')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Research Teams',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='researcharticle',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='core.researchteam'),
        ),
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_articles', to='core.student')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.researcharticle')),
            ],
            options={
                'verbose_name_plural': 'Article Likes',
                'unique_together': {('article', 'student')},
            },
        ),
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('explanation', models.TextField(help_text='Explain your solution process')),
                ('attachments', cloudinary.models.CloudinaryField(blank=True, help_text='Optional: diagrams, calculations, etc.', max_length=255, null=True, verbose_name='file')),
                ('is_awarded', models.BooleanField(default=False)),
                ('award_comment', models.TextField(blank=True, null=True)),
                ('awarded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_quizzes', to=settings.AUTH_USER_MODEL)),
                ('guest_submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_submissions', to='core.guestcontributor')),
                ('student_submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_submissions', to='core.student')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.researchquiz')),
            ],
            options={
                'verbose_name_plural': 'Quiz Submissions',
                'ordering': ['-created_at'],
                'unique_together': {('quiz', 'student_submitter', 'guest_submitter')},
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='Member', help_text='e.g., Member, Co-Lead', max_length=100)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_teams', to='core.student')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.researchteam')),
            ],
            options={
                'verbose_name_plural': 'Team Memberships',
                'ordering': ['-joined_at'],
                'unique_together': {('team', 'student')},
            },
        ),
    ]
