# Generated by Django 5.2.4 on 2025-10-19 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_guestcontributor_researcharticle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchteam',
            name='team_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to='core.student'),
        ),
    ]
