# Generated by Django 4.2.7 on 2025-11-10 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_researchteam_team_lead'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizsubmission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='departmentaldues',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of payment submission', null=True),
        ),
        migrations.AddField(
            model_name='departmentaldues',
            name='last_printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departmentaldues',
            name='print_count',
            field=models.IntegerField(default=0, help_text='Number of times receipt was printed'),
        ),
        migrations.AddField(
            model_name='departmentaldues',
            name='qr_code_data',
            field=models.TextField(blank=True, help_text='QR code data for verification'),
        ),
        migrations.AddField(
            model_name='departmentaldues',
            name='security_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash for verification', max_length=64),
        ),
        migrations.CreateModel(
            name='ReceiptVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(max_length=100)),
                ('is_valid', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='core.departmentaldues')),
            ],
            options={
                'ordering': ['-verified_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptPrintLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('printed_by_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_logs', to='core.departmentaldues')),
            ],
            options={
                'verbose_name_plural': 'Receipt Print Logs',
                'ordering': ['-printed_at'],
            },
        ),
    ]
