# Generated by Django 4.2.7 on 2025-11-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_quizsubmission_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=1, help_text='Hashed password', max_length=128),
            preserve_default=False,
        ),
    ]
