# Generated by Django 4.2.7 on 2025-11-13 08:11

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_student_has_paid_student_payment_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestcontributor',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='guestcontributor',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guestcontributor',
            name='payment_proof',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Screenshot of bank transfer', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='guestcontributor',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='guestcontributor',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='guestcontributor',
            name='transaction_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='researcharticle',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='attachments',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='explanation',
            field=models.TextField(help_text='Detailed step-by-step explanation'),
        ),
        migrations.AlterField(
            model_name='researcharticle',
            name='abstract',
            field=models.TextField(help_text='Introduction/Brief overview created by Director'),
        ),
        migrations.AlterField(
            model_name='researcharticle',
            name='created_by',
            field=models.ForeignKey(help_text='Director of Research', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='researchcontribution',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Proofreader who approved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='researchcontribution',
            name='references',
            field=models.TextField(blank=True, help_text='Optional citations', null=True),
        ),
        migrations.AlterField(
            model_name='researchcontribution',
            name='section_order',
            field=models.IntegerField(default=0, help_text='Display order assigned by proofreader'),
        ),
        migrations.AlterField(
            model_name='researchcontribution',
            name='section_title',
            field=models.CharField(choices=[('Introduction', 'Introduction'), ('Background/Definition', 'Background/Definition'), ('Main Body', 'Main Body'), ('Connection/Integration', 'Connection/Integration'), ('Conclusion', 'Conclusion')], max_length=300),
        ),
        migrations.AlterField(
            model_name='researchquiz',
            name='hints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchquiz',
            name='points',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='researchteam',
            name='max_members',
            field=models.IntegerField(default=15, help_text='Maximum 15 members per team'),
        ),
        migrations.AlterField(
            model_name='researchteam',
            name='team_lead',
            field=models.ForeignKey(blank=True, help_text='Director of Research assigns team lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to='core.student'),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='role',
            field=models.CharField(choices=[('Researcher', 'Researcher'), ('Writer', 'Writer'), ('Proofreader', 'Proofreader'), ('Graphic Designer', 'Graphic Designer')], default='Researcher', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='quizsubmission',
            unique_together={('quiz', 'student_submitter'), ('quiz', 'guest_submitter')},
        ),
        migrations.CreateModel(
            name='ResearchClubRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('payment_reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('payment_proof', cloudinary.models.CloudinaryField(blank=True, help_text='Screenshot of bank transfer', max_length=255, null=True, verbose_name='image')),
                ('transaction_description', models.CharField(blank=True, help_text='Description used in bank transfer', max_length=200)),
                ('payment_date', models.DateField(blank=True, help_text='Date of payment as shown on receipt', null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_research_registrations', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='research_club_registration', to='core.student')),
            ],
            options={
                'verbose_name_plural': 'Research Club Registrations',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.researcharticle')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to='core.student')),
            ],
            options={
                'verbose_name_plural': 'Article Comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
