# Generated by Django 4.2.7 on 2025-11-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_guestcontributor_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryresource',
            name='category',
            field=models.CharField(choices=[('Textbook', 'Textbook'), ('Journal', 'Journal Article'), ('Lecture', 'Lecture Notes'), ('Project', 'Project Report'), ('Thesis', 'Thesis'), ('Constitution', 'Nabes Constitution'), ('Other', 'Other')], max_length=20),
        ),
    ]
