# Generated by Django 4.2.7 on 2025-11-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_libraryresource_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastquestion',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
