# Generated by Django 5.0 on 2026-01-15 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_pastquestion_year"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("paystack", "Paystack Payment"), ("pin", "Access PIN")],
                help_text="How the student paid for portal access",
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="AccessPin",
            fields=[
                (
                    "pin",
                    models.CharField(
                        max_length=12, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("used", "Used"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Optional expiry date", null=True
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        blank=True,
                        help_text="For bulk generation tracking",
                        max_length=50,
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_pins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "used_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="used_pin",
                        to="core.student",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Access Pins",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.AddField(
            model_name="student",
            name="access_pin_used",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registered_student",
                to="core.accesspin",
            ),
        ),
        migrations.CreateModel(
            name="PinUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_reg_number", models.CharField(blank=True, max_length=50)),
                ("attempt_successful", models.BooleanField(default=False)),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "pin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="core.accesspin",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "PIN Usage Logs",
                "ordering": ["-attempted_at"],
            },
        ),
    ]
