# Generated by Django 5.0 on 2026-01-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_student_payment_method_accesspin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exco",
            name="is_msrc",
            field=models.BooleanField(
                default=False,
                help_text="Check if this person is a Member of Student Representative Council (MSRC)",
            ),
        ),
    ]
