# Generated by Django 5.0 on 2026-01-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_exco_is_msrc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesspin",
            name="pin",
            field=models.CharField(
                max_length=20, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
