# Generated by Django 5.0 on 2026-02-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_accesspin_pin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exco",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
