# Generated by Django 4.2.28 on 2026-04-05 18:06

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0015_alter_exco_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departmentaldues",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
        ),
        migrations.CreateModel(
            name="IDCardApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "passport_photo",
                    cloudinary.models.CloudinaryField(
                        help_text="Upload a clear passport photograph (white background, face visible)",
                        max_length=255,
                        verbose_name="image",
                    ),
                ),
                (
                    "academic_session",
                    models.CharField(help_text="e.g., 2024/2025", max_length=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("printed", "Printed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_id_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_card_application",
                        to="core.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "ID Card Application",
                "verbose_name_plural": "ID Card Applications",
                "ordering": ["-applied_at"],
            },
        ),
    ]
