# Generated by Django 4.2.28 on 2026-04-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_alter_departmentaldues_amount_paid_idcardapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="pinusagelog",
            name="others",
            field=models.CharField(blank=True, null=True),
        ),
    ]
